- name: Toucher .profile
  file:
    path: "/home/{{ ident|upper }}/.profile"
    state: touch
  become_user: "{{ ident|upper }}"

- name: Lager katalogen .local/bin
  file:
    path: "/home/{{ ident|upper }}/.local/bin"
    state: directory
    mode: 0750
  become_user: "{{ ident|upper }}"

- name: Legg til .local/bin i path
  lineinfile:
    path: "/home/{{ ident|upper }}/.profile"
    regexp: '/\.local/bin'
    line: "export PATH=$PATH:/home/{{ ident|upper}}/.local/bin"

- name: Lager katalogen workspace
  file:
    path: "/home/{{ ident|upper }}/workspace"
    state: directory
    mode: 0750
  become_user: "{{ ident|upper }}"

- name: Git clone kubeconfig
  git:
    repo: "http://{{ ident|upper }}:{{ ident_password }}@stash.devillo.no/scm/aura/kubeconfigs.git"
    dest: "/home/{{ ident|upper }}/kubeconfigs"
  become_user: "{{ ident|upper }}"

- name: KUBECONFIG miljøvariabel
  lineinfile:
    path: "/home/{{ ident|upper }}/.bashrc"
    regexp: 'export KUBECONFIG='
    line: "export KUBECONFIG=/home/{{ ident|upper }}/kubeconfigs/config"

- name: Git clone kubectx
  git:
    repo: https://github.com/ahmetb/kubectx.git
    dest: "/home/{{ ident|upper }}/workspace/kubectx"
  become_user: "{{ ident|upper }}"

- name: Gjør kubectx kjørbar
  file:
    path: "/home/{{ ident|upper }}/workspace/kubectx/kubectx"
    mode: 0755

- name: Symlink kubectx
  file:
    path: "/home/{{ ident|upper }}/.local/bin/kubectx"
    src: "/home/{{ ident|upper }}/workspace/kubectx/kubectx"
    state: link
  become_user: "{{ ident|upper }}"

- name: Legger til autocompletions for kubectx
  lineinfile:
    path: "/home/{{ ident|upper }}/.bashrc"
    regexp: 'source /home/{{ ident|upper }}/workspace/kubectx/completion/kubectx.bash'
    line: "source /home/{{ ident|upper }}/workspace/kubectx/completion/kubectx.bash"

- name: Gjør kubens kjørbar
  file:
    path: "/home/{{ ident|upper }}/workspace/kubectx/kubens"
    mode: 0755

- name: Symlink kubens
  file:
    path: "/home/{{ ident|upper }}/.local/bin/kubens"
    src: "/home/{{ ident|upper }}/workspace/kubectx/kubens"
    state: link
  become_user: "{{ ident|upper }}"

- name: Legger til autocmopletions for kubens
  lineinfile:
    path: "/home/{{ ident|upper }}/.bashrc"
    regexp: 'source /home/{{ ident|upper }}/workspace/kubectx/completion/kubens.bash'
    line: "source /home/{{ ident|upper }}/workspace/kubectx/completion/kubens.bash"

- name: Gjør utils.bash kjørbar
  file:
    path: "/home/{{ ident|upper }}/workspace/kubectx/utils.bash"
    mode: 0755

- name: Symlink utils.bash
  file:
    path: "/home/{{ ident|upper }}/.local/bin/utils.bash"
    src: "/home/{{ ident|upper }}/workspace/kubectx/utils.bash"
    state: link
  become_user: "{{ ident|upper }}"
