- name: Toucher .profile
  file:
    path: "/home/{{ ident|upper }}/.profile"
    state: touch
  become_user: "{{ ident|upper }}"

- name: Lager katalogen workspace
  file:
    path: "/home/{{ ident|upper }}/workspace"
    state: directory
    mode: 0750
  become_user: "{{ ident|upper }}"

- name: Git clone kubeconfig
  git:
    repo: "http://{{ ident|upper }}:{{ ident_password }}@stash.devillo.no/scm/aura/kubeconfigs.git"
    dest: "/home/{{ ident|upper }}/kubeconfigs"
  become_user: "{{ ident|upper }}"

- name: Git clone kubectx
  git:
    repo: https://github.com/ahmetb/kubectx.git
    dest: "/home/{{ ident|upper }}/workspace/kubectx"
  become_user: "{{ ident|upper }}"

- name: Gjør kubectx kjørbar
  file:
    path: "/home/{{ ident|upper }}/workspace/kubectx/kubectx"
    mode: 0755

- name: Symlink kubectx
  file:
    path: "/home/{{ ident|upper }}/.local/bin/kubectx"
    src: "/home/{{ ident|upper }}/workspace/kubectx/kubectx"
    state: link
  become_user: "{{ ident|upper }}"

- name: Gjør kubens kjørbar
  file:
    path: "/home/{{ ident|upper }}/workspace/kubectx/kubens"
    mode: 0755

- name: Symlink kubens
  file:
    path: "/home/{{ ident|upper }}/.local/bin/kubens"
    src: "/home/{{ ident|upper }}/workspace/kubectx/kubens"
    state: link
  become_user: "{{ ident|upper }}"

- name: Gjør utils.bash kjørbar
  file:
    path: "/home/{{ ident|upper }}/workspace/kubectx/utils.bash"
    mode: 0755

- name: Symlink utils.bash
  file:
    path: "/home/{{ ident|upper }}/.local/bin/utils.bash"
    src: "/home/{{ ident|upper }}/workspace/kubectx/utils.bash"
    state: link
  become_user: "{{ ident|upper }}"

- name: Completions og KUBECONFIG
  copy:
    src: files/etc_profiled_nav.sh
    dest: /etc/profile.d/nav.sh
