- hosts: all
  become: yes
  vars_prompt:
    - name: "githubusername"
      prompt: "Enter your GitHub username"
      private: no
    - name: "githubpassword"
      prompt: "Enter your GitHub password/OAuth token"
      private: yes
  roles:
    - certificates
    - docker
    - kubernetes
    - common

- hosts: jenkins
  become: yes
  roles:
    - jenkins

- hosts: linuximage
  become: yes
  vars_prompt:
    - name: "ident"
      prompt: "Enter your NAV ident"
      private: no
    - name: "ident_domain"
      prompt: "Enter domain"
      default: "adeo.no"
      private: no
    - name: "ident_password"
      prompt: "Enter your NAV password"
      private: yes
  roles:
    - linuximage
    - vmware-viewagent
    - firefox
    - jetbrains
    - kubeconfigs
