- name: "download ideaIU-{{ idea_version }}"
  get_url:
    url: "https://download.jetbrains.com/idea/ideaIU-{{ idea_version }}.tar.gz"
    dest: "/opt/ideaIU-{{ idea_version }}.tar.gz"
    timeout: 180

- name: create intellij install dir
  file: path=/opt/ideaIU state=directory

- name: "unpack ideaIU-{{ idea_version }}"
  cmd: "tar -xzf /opt/ideaIU-{{ idea_version }}.tar.gz -C /opt/ideaIU --strip-components 1"

- name: symlink idea.sh
  file:
    dest: /usr/bin/idea
    src: /opt/ideaIU/bin/idea.sh
    state: link

- name: create intellij desktop entry
  block:
    - template:
        src: files/jetbrains-idea.desktop
        dest: /usr/share/applications/jetbrains-idea.desktop
    - copy:
        src: /opt/ideaIU/bin/idea.png
        dest: /usr/share/icons/hicolor/128x128/apps/idea.png
        remote_src: yes
