- block:
    - name: clone ca-certificates
      git:
        repo: "https://{{ githubusername }}:{{ githubpassword }}@github.com/navikt/ca-certificates.git"
        dest: /opt/ca-certificates
        force: yes
    - name: install certs
      command: ./install-certs.sh /etc/pki/ca-trust/source/anchors
      args:
        chdir: /opt/ca-certificates
  when: githubpassword is defined and githubpassword != ""

- name: Install certs
  copy:
    src: /etc/pki/tls/certs/{{ item }}
    dest: /etc/pki/ca-trust/source/anchors/{{ item }}
    remote_src: yes
  with_items:
    - NAV_Issuing_Intern_CA.crt
    - NAV_issuing_CA.crt
    - NAV_root_CA.crt
    - NAV_sub_CA.crt
    - B27_Issuing_CA.crt
    - B27_Issuing_CA_Intern.crt
    - B27_root_CA.crt
    - B27_sub_CA.crt
    - D26_Issuing_CA.crt
    - D26_Issuing_Intern_CA.crt
    - D26_root_CA.crt
    - D26_sub_CA.crt
    - E34_Issuing_CA.crt
    - E34_Issuing_CA_Utvikling_CA.crt
    - E34_root_CA.crt
    - E34_sub_CA.crt
  when: githubpassword is not defined or githubpassword == ""

- name: Enable update-ca-trust
  command: /usr/bin/update-ca-trust
