- name: Add kubernetes repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes
    file: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: true
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: true
    repo_gpgcheck: true
    state: present

- name: Add kubernetes key
  rpm_key:
    state: present
    key: "{{ item }}"
  with_items:
    - https://packages.cloud.google.com/yum/doc/yum-key.gpg
    - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install kubectl
  yum:
    name: "kubectl-{{ kubectl_version }}"
    state: present
    update_cache: yes

- name: Lager katalogen .local/bin
  file:
    path: "/home/{{ ident|upper }}/.local/bin"
    state: directory
    mode: 0750

- name: Legg til $USER/.local/bin i path
  lineinfile:
    path: "/home/{{ ident|upper }}/.profile"
    regex: "/.local/bin"
    line: "export PATH=$PATH:/home/{{ ident|upper}}/.local/bin"

- name: Lager katalogen $USER/workspace
  file:
    path: "/home/{{ ident|upper }}/workspace"
    state: directory
    mode: 0750
