- name: Add Jenkins repository
  yum_repository:
    name: Jenkins
    description: Jenkins
    baseurl: https://pkg.jenkins.io/redhat-stable
    enabled: true
    gpgcheck: true
    state: present

- name: Add Jenkins key
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: install latest jenkins
  yum:
    name: jenkins
    state: latest

- name: Add jenkins to docker group
  user:
    name: jenkins
    group: docker
    append: yes

- name: Setup jenkins git config
  template:
    src: templates/gitconfig.j2
    dest: /var/lib/jenkins/.gitconfig
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Enable and start jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes
