- name: install java
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - java-1.7.0-openjdk-devel
    - java-1.8.0-openjdk-devel

- name: set java 1.8 as default
  command: /usr/sbin/alternatives --set java java-1.8.0-openjdk.x86_64
