- include: firefox.yaml
- include: chrome.yaml
- include: java.yaml
- include: maven.yaml
- include: node.yaml
- name: install git
  yum:
    name: git
    state: latest
- name: Specifying subnet for vmware-viewagent
  lineinfile:
    dest: /etc/vmware/viewagent-custom.conf
    regexp: '#?Subnet='
    line: "Subnet={{ vmware_subnet }}"
