- name: "Download and Install node-{{ node_version }}"
  unarchive:
    src: "https://nodejs.org/dist/v{{ node_version }}/node-v{{ node_version }}-linux-x64.tar.xz"
    dest: /opt
    remote_src: yes

- name: "Install alternative node-{{ node_version }}"
  command: >
    /usr/sbin/alternatives
      --install /usr/bin/node node /opt/node-v{{ node_version }}-linux-x64/bin/node {{ item|replace(".", "") }}
      --family node-{{ node_version }}
      --slave /usr/bin/npm npm /opt/node-v{{ node_version }}-linux-x64/bin/npm

- name: "set nodejs {{ node_version }} as default"
  command: "/usr/sbin/alternatives --set node node-{{ node_version }}"

- name: Setup npmrc
  copy: src=files/npmrc dest=/etc/npmrc
  when: proxy_env.http_proxy|default("") != ""
